apiVersion: v1
kind: Service
metadata:
  name: vernemq
  labels:
    app: broker
    tier: backend
spec:
  selector:
    app: broker
    tier: backend
  ports:
  - port: 8080
    targetPort: 80
    name: websock
  - port: 1883
    targetPort: 1883
    name: mqtt
